"""create companies table

Revision ID: 0632ff9e58fb
Revises: 
Create Date: 2026-08-19 23:47:49.844836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0632ff9e58fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('employees', sa.Integer(), nullable=False),
    sa.Column('business_model', sa.String(length=255), nullable=True),
    sa.Column('products', sa.Text(), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('customers', sa.Text(), nullable=True),
    sa.Column('suppliers', sa.Text(), nullable=True),
    sa.Column('revenue_range', sa.String(length=50), nullable=True),
    sa.Column('tools_used', sa.Text(), nullable=True),
    sa.Column('objectives', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
