"""add transaction indexes

Revision ID: 214c9d63a123
Revises: 3f91e321231d
Create Date: 2026-09-02 00:19:47.643793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214c9d63a123'
down_revision: Union[str, Sequence[str], None] = '3f91e321231d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_company_status_date', 'transactions', ['company_id', 'status', 'date'], unique=False)
    op.create_index('ix_transactions_import_id', 'transactions', ['import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_import_id', table_name='transactions')
    op.drop_index('ix_transactions_company_status_date', table_name='transactions')
    # ### end Alembic commands ###
