"""add company currency

Revision ID: 3a95a53031ff
Revises: 214c9d63a123
Create Date: 2026-09-02 06:27:25.894491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a95a53031ff'
down_revision: Union[str, Sequence[str], None] = '214c9d63a123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('currency', sa.String(length=3), server_default='CAD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'currency')
    # ### end Alembic commands ###
