"""add company piloting thresholds

Revision ID: 3f91e321231d
Revises: b2c3d4e5f6a7
Create Date: 2026-09-01 20:17:06.556668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f91e321231d'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('target_margin_pct', sa.Numeric(precision=5, scale=2), server_default='20', nullable=False))
    op.add_column('companies', sa.Column('revenue_target', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('companies', sa.Column('expense_budget', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('companies', sa.Column('health_healthy_threshold', sa.Integer(), server_default='80', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'health_healthy_threshold')
    op.drop_column('companies', 'expense_budget')
    op.drop_column('companies', 'revenue_target')
    op.drop_column('companies', 'target_margin_pct')
    # ### end Alembic commands ###
