"""create actions table

Revision ID: b4b400124ddc
Revises: 3a95a53031ff
Create Date: 2026-09-02 16:17:27.550020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b400124ddc'
down_revision: Union[str, Sequence[str], None] = '3a95a53031ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('metric_category', sa.String(length=255), nullable=True),
    sa.Column('baseline_start', sa.Date(), nullable=False),
    sa.Column('baseline_end', sa.Date(), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outcome_start', sa.Date(), nullable=True),
    sa.Column('outcome_end', sa.Date(), nullable=True),
    sa.Column('outcome_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('outcome_measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actions_company_status', 'actions', ['company_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_actions_company_status', table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
